### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by GreatGodOfFire** [yanpuri/Stratagem-UCI-Chess-Engine#10]
As previous issues (namely, #1, #3, #4, #5, #6, #7, #8 and #9) have pointed out, this code is a copy of GPLv3 licensed code ([Alexandria](https://github.com/PGG106/Alexandria)) without proper acknowledgment.
Under the assumption that you did this best faith (even though your Reddit post shows you didn't), I would like you to tell you a bit about the licensing of code.
There are many licenses used for code, but one of the most popular is GPLv3, also used for Alexandria.
GPLv3 has some requirements if someone uses the code licensed with it, which you can find [on tldrlegal.com](https://www.tldrlegal.com/license/gnu-general-public-license-v3-gpl-3).
Failure to follow these requirements can cause legal trouble, most likely a DMCA claim.
Therefore it is not wise to copy the code of others without following the license they used.

I would recommend either deleting this repository or following the terms of the GPLv3 license to avoid any problems :D

Regards,
Me

**Comment by yanpuri** [comment]
What reddit post

**Comment by yanpuri** [comment]
That's mean

**Comment by GreatGodOfFire** [comment]
Just closing issues doesn't fix them
